# Generated by Django 2.1.4 on 2019-03-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackmcgillApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackadmin',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='hackadmin',
            name='Last_name',
        ),
    ]
